name: 'Prepare MacOS system'
description: 'Prepare system for building R packages'
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        echo "::group::Removing Homebrew"
        cp $(which gtar) $(which zstd) .
        brew unlink $(brew list --formula) || true
        sudo rm -vf $(which brew)
        sudo mv /usr/local/Homebrew /usr/local/oldhomebrew
        sudo mv /usr/local/Cellar /usr/local/oldcellar
        cp -f gtar zstd /usr/local/bin/
        hash -r
        echo "Done removing homebrew!"
        echo "::endgroup::"

    - shell: bash
      run: |
        if [ -d "/opt/X11/lib" ]; then
          echo "/opt/X11/lib exists. Skipping xQuartz installation"
        else
          echo "::group::Installing XQuartz"
          echo "Downloading XQuartz..."
          curl --retry 3 -fLo XQuartz-2.8.1.dmg https://github.com/XQuartz/XQuartz/releases/download/XQuartz-2.8.1/XQuartz-2.8.1.dmg
          sudo hdiutil attach XQuartz-2.8.1.dmg -mountpoint /Volumes/xquartz
          sudo installer -pkg "/Volumes/xquartz/XQuartz.pkg" -target /
          sudo hdiutil detach /Volumes/xquartz
          rm -f XQuartz-2.8.1.dmg
          echo "Done installing XQuartz!"
          echo "::endgroup::"
        fi

    - shell: bash
      run: |
        if [ -d "/usr/local/gfortran" ]; then
          echo "/usr/local/gfortran exists. Skipping fortran installation"
        else
          echo "::group::Installing Fortran"
          echo "Downloading Fortran..."
          curl --retry 3 -fLo /tmp/gfortran82.dmg https://github.com/fxcoudert/gfortran-for-macOS/releases/download/8.2/gfortran-8.2-Mojave.dmg
          sudo hdiutil attach /tmp/gfortran82.dmg -mountpoint /Volumes/gfortran
          sudo installer -pkg "/Volumes/gfortran/gfortran-8.2-Mojave/gfortran.pkg" -target /
          sudo hdiutil detach /Volumes/gfortran
          rm -f /tmp/gfortran82.dmg
          echo "Done installing Fortran!"
          echo "::endgroup::"
        fi

    - shell: bash
      run: |
        if pandoc --version; then
          echo "Skipping pandoc installation"
        else
          echo "::group::Installing Pandoc"
          curl --retry 3 -fOL https://github.com/jgm/pandoc/releases/download/2.14.2/pandoc-2.14.2-macOS.pkg
          sudo installer -pkg pandoc-2.14.2-macOS.pkg -target /
          rm -f pandoc-2.14.2-macOS.pkg
          echo "::endgroup::"
        fi

    - shell: bash
      run: |
        echo "::group::Installing autobrew CRAN bundle"
        curl --retry 3 -fsSL https://github.com/autobrew/bundler/releases/download/2022-03-18/cranbundle-20220318-high_sierra.tar.xz -o libs.tar.xz
        sudo tar -xf libs.tar.xz --strip 1 -C /usr/local/
        rm -f libs.tar.xz
        echo "Done installing autobrew CRAN bundle!"
        echo "::endgroup::"

    - shell: bash
      run:
        echo "Setting path to proj and fortran"
        echo "/usr/local/gfortran/bin" >> $GITHUB_PATH
